server:
  port: 8079

spring:
  application:
    name: mail_service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Mail configuration
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

# Configuration for Eureka server registration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# Configuration values
confirmationAddress: http://localhost:8082/api/v1/registration-service/registration/confirm?token=