services:
  user_service_db:
    container_name: user_service_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./user_service/docker:/scripts
      - user_service_db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - user_service_db_network
    restart: unless-stopped


  account_service_db:
    container_name: account_service_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./account_service/docker:/scripts
      - account_service_db:/data/postgres
    ports:
      - "5431:5432"
    networks:
      - account_service_db_network
    restart: unless-stopped

  registration_service_db:
    container_name: registration_service_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./registration_service/docker:/scripts
      - registration_service_db:/data/postgres
    ports:
      - "5430:5432"
    networks:
      - registration_service_db_network
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - user_service_db_network
      - account_service_db_network
      - registration_service_db_network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq

networks:
  user_service_db_network:
    driver: bridge
  account_service_db_network:
    driver: bridge
  registration_service_db_network:
    driver: bridge
  rabbitmq:
    driver: bridge

volumes:
  user_service_db:
  account_service_db:
  registration_service_db:
  pgadmin: