server:
  port: 8080

spring:
  application:
    name: app_user_application
  datasource:
    url: jdbc:postgresql://localhost:5432/appuser
    username: developer
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true