server:
  port: 8080

spring:
  application:
    name: app_user_application
  datasource:
    url: jdbc:postgresql://localhost:5432/app_user_db
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true