server:
  port: 8080

spring:
  application:
    name: user_service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Configuration for Eureka server registration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true