server:
  port: 8081

spring:
  application:
    name: account_service
  datasource:
    url: jdbc:postgresql://localhost:5431/account_service_db
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Configuration for Eureka server registration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true